### PR TITLE
Review api routes

### PR DESCRIPTION
**Pull request by samcomma**
**Routes:**
- added get (all), get (by id), post, put, delete routes for Review model

**Seeding:**
- added Review model seed data (using Steven's function)

### CODE REVIEW

**Review by j-e-torres — DISMISSED** [review]
Looks dandy to me

**Review by slevine111 — DISMISSED** [review]

**Comment by laurenwest12** [comment]
Looks good, but something I noticed is that some of routes are returning the createdSeedInstances function and some of us are not. For my routes I did not return the data and it still seeded without a problem - is the return statement redundant since the function already returns the seed?

More a general question for consistency than specifically on this PR. PR looks good.

**Review by laurenwest12 — DISMISSED** [review]

**Comment by slevine111** [comment]
@samcomma Two requests, if you don’t mind. Can you move the products .then block to before the lineitem.then block so I can add a product to each lineitem? Two, can you put return in front of each of the createdSeedInstances that don’t have one? Otherwise, it will move onto the next .then before the data for that table is finished seeding

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by samcomma** [comment]
@slevine111 I've made those updates... should be good to merge now if 2 peeps wanna review/approve!

**Review by slevine111 — APPROVED** [review]
Thanks! Approved

**Review by laurenwest12 — APPROVED** [review]

**Pull request merged**
