### PR TITLE
Login and logout changes

### PR DESCRIPTION
**Pull request by slevine111**
- Put processAfterLogin thunk into authentication thunks for logging user in and checking if user is logged in on hard reload
- Fixed bug with login for users with no order of status = cart
- Reset cart, userlineitem, and userorder reducers ot empty when user logs out
- Set redux-logger to not be used when environment variable indicates is in production (have to test in heroku)

### CODE REVIEW

**Review by laurenwest12 — DISMISSED** [review]
Looks good. This actually might fix the problem I had with the sign up / log in and not being able to add items to the cart. We'll see if it ends up working once both are merges.

**Review by j-e-torres — DISMISSED** [review]
good stuff here, I see you also brought the logout code from component to store as well

**Review by laurenwest12 — DISMISSED** [review]
Looks good, hopefully will fix the issues with sign up and creating a new cart

**Review by samcomma — DISMISSED** [review]

**Review by laurenwest12 — APPROVED** [review]
Approved again, had to resolve a small conflict

**Review by j-e-torres — APPROVED** [review]
Copy that

**Pull request merged**
