### PR TITLE
User api

### PR DESCRIPTION
**Pull request by j-e-torres**
added app.use router in db/index.js, created get and delete routes for api/User and added some User.create users in db/seed

### CODE REVIEW

**Review by slevine111 — COMMENTED** [review]
Looks all good to me. Only thing is wondering did you check that the api route works?

**Comment by j-e-torres** [comment]
Not yet, let me test when I get home in a bit

Regards,
Juan

**Comment by j-e-torres** [comment]
Okay, fixed some typos and pathnames, also installed postgres as it wasn't installed. I just tested the GET route and it works.  Not sure how to test delete route as it is right now

**Review by slevine111 — APPROVED** [review]
Looks good to me. Approving it now. But yea we have enough code now where we are able to spin up an server so I think should definitely be testing anything before putting in a PR (if not writing actual test but I know that requires a lot more time)
Have you ever used Postman? That's a really easy to test any type of route, i.e. more than just GET routes. I'll show you it on Tuesday if you haven't

**Comment by j-e-torres** [comment]
Ah okay, I'll look into it if I got time

**Review by samcomma — APPROVED** [review]

**Pull request merged**
