### PR TITLE
Updated package.json

### PR DESCRIPTION
**Pull request by slevine111**
moved all babel and webpack packages to dev dependencies and installed nodemon as dev dependency (following Elliot's lead of never relying on packages installed globally)

### CODE REVIEW

**Review by j-e-torres — COMMENTED** [review]
I see more updated versions of things, would we still have to change babel-loader to version 7?

**Review by samcomma — APPROVED** [review]
Makes sense to me. Updated package.json looks good

**Comment by laurenwest12** [comment]
Makes sense, but do we also need to update our package-lock to reflect the version changes?

**Comment by slevine111** [comment]
@j-e-torres babel-loader is at version 8 (version 7 doesn’t work with @babel packages). Looks like it wasn’t one of the packages whose package got updated with my update.
@laurenwest12 the package-lock file also got updated (see how there are two files changed at the top of the pr). That file automatically gets updated when a package is updated as I did not go in and manually change the file when i changed the package.json file

**Review by j-e-torres — APPROVED** [review]

**Pull request merged**
