### PR TITLE
Admin page

### PR DESCRIPTION
**Pull request by j-e-torres**
Started AdminPage
- added Administrator to nav bar as I was having trouble rendering 2 other ways
- fixed a typo in our redux Constants
- added backend route to grab all orders with 'in-progress status'
  - thus creating the const/actions/reducer for redux
- in admin page can list all products 
  - each product when rendered has edit and delete button(non functional)
  - has add product button at top

### CODE REVIEW

**Review by slevine111 — DISMISSED** [review]
looks great! Did you try rendering the page with a “go to admin page” button on the my account page? That’s what I was thinking a bit

I also caught that typo in PR I’m about to submit.

One other food for thought and this also applies to the my account front-end route. And it’s certainly a case of optimization don’t have to consider unless we magically have the time. Now getting to it. That :userId in the front end route is probably not necessary, for the reason that page is going to look the same for every user

**Comment by j-e-torres** [comment]
My first attempt was to have the admin button on the my account link, but it wouldn't necessarily render the component, I'll actually try again doing it that way if I get a chance at work if not, during class

As for the userId I shall refactor the comoponent code

**Review by laurenwest12 — APPROVED** [review]
Looks good

**Review by slevine111 — APPROVED** [review]
looks great!

**Pull request merged**
